#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import pandas as pd



#read similarity scores generated by three methods
cos_all_features=pd.read_csv('./cos_similarity/cos_all_features.csv')

jaccard_all_features=pd.read_csv('./jaccard_similarity/jaccard_all_features.csv')

edit_v_all_features=pd.read_csv('./edit_value_similarity/edit_v_all_features.csv')


#calculate their average socre
cos=cos_all_features.describe()["Similarity_score"]
jaccard=jaccard_all_features.describe()["Similarity_score"]
edit_v=edit_v_all_features.describe()["Similarity_score"]

#merge them together and compare
all_fearures= pd.concat([cos,jaccard,edit_v], axis=1)
all_fearures.columns=["cosine similarity","jaccard similarity","edit_value similarity"]
print(all_fearures)

